services:
  - type: web
    name: yoquet-disenos-backend
    env: python
    plan: free
    runtime: python
    buildCommand: >
      pip install --upgrade pip setuptools wheel &&
      pip install -r requirements.txt &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.prod
      - key: DJANGO_SECRET_KEY
        value: tu_clave_ultra_segura
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: yoquet-disenos-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://omargonza.github.io,https://omargonza.github.io/yoquet_disenos_frontend
      - key: CSRF_TRUSTED_ORIGINS
        value: https://yoquet-disenos-backend.onrender.com,https://omargonza.github.io
      - key: DATABASE_URL
        value: postgresql://aplicacionesgonza@gmail.com:full@1234567899@host:5432/yoquet_full

buildCommand: |
  pip install -r requirements.txt
  python manage.py collectstatic --noinput
  python manage.py migrate
startCommand: gunicorn backend.wsgi:application