# Generated by Django 5.1.2 on 2025-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_orden_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='hash_imagen',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
