# Generated by Django 5.1.2 on 2025-11-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_hash_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='hash_imagen',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
